version: "3"

services:
  database:
    image: mysql
    container_name: parkcoitdb
    volumes:
      - ~/docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/var/lib/mysql:/var/lib/mysql:ro
      - ~/docker/mysql/var/log/mysql:/var/log/mysql:ro
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - 3306:3306
  web:
    image:  parkcoitdj:v1
    build: .
    container_name: parkcoitdj
    command:
      - python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/parkcoitdj
    expose:
      - "8000"