# Generated by Django 4.1.3 on 2022-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.TextField(verbose_name=120)),
                ('nickname', models.TextField(verbose_name=20)),
                ('password', models.TextField(verbose_name=255)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'muser',
            },
        ),
    ]
