# Generated by Django 4.1.3 on 2022-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.TextField(verbose_name=100)),
                ('password', models.TextField(verbose_name=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
