# Generated by Django 4.1.3 on 2022-12-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_users', '0001_initial'),
        ('products', '0001_initial'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliveries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_users.user')),
            ],
            options={
                'db_table': 'shop_orders',
            },
        ),
    ]
