# Generated by Django 4.1.3 on 2022-11-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='cinema',
        ),
    ]
